<?php
namespace FSS\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 12:58:05.
 */
class AddressTest extends \PHPUnit\Framework\TestCase
{

    /**
     *
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Address();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers FSS\Models\Address::city_data
     * 
     * @todo Implement testCity_data().
     */
    public function testCity_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\Address::state_data
     * 
     * @todo Implement testState_data().
     */
    public function testState_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\Address::county_data
     * 
     * @todo Implement testCounty_data().
     */
    public function testCounty_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
