<?php
namespace FSS\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 13:02:09.
 */
class City_data_extendedControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var City_data_extendedController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new City_data_extendedController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers FSS\Controllers\City_data_extendedController::read
     * 
     * @todo Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Controllers\City_data_extendedController::readAll
     * 
     * @todo Implement testReadAll().
     */
    public function testReadAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Controllers\City_data_extendedController::readAllWithFilter
     * 
     * @todo Implement testReadAllWithFilter().
     */
    public function testReadAllWithFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Controllers\City_data_extendedController::create
     * 
     * @todo Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Controllers\City_data_extendedController::update
     * 
     * @todo Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Controllers\City_data_extendedController::delete
     * 
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
