<?php
namespace FSS\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 12:58:06.
 */
class Client_ethnicityTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var Client_ethnicity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Client_ethnicity();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers FSS\Models\Client_ethnicity::client
     * 
     * @todo Implement testClient().
     */
    public function testClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\Client_ethnicity::ethnicity
     * 
     * @todo Implement testEthnicity().
     */
    public function testEthnicity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
