<?php
namespace FSS\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 13:02:09.
 */
class Counselee_child_bio_parentControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Counselee_child_bio_parentController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Counselee_child_bio_parentController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::readAll
     * @todo   Implement testReadAll().
     */
    public function testReadAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::readAllWithFilter
     * @todo   Implement testReadAllWithFilter().
     */
    public function testReadAllWithFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Counselee_child_bio_parentController::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
