<?php
namespace FSS\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 12:58:06.
 */
class Counselee_drug_useTest extends \PHPUnit\Framework\TestCase
{

    /**
     *
     * @var Counselee_drug_use
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Counselee_drug_use();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}
}
