<?php
namespace FSS\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 13:02:11.
 */
class Shelter_client_identity_preferenceControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Shelter_client_identity_preferenceController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Shelter_client_identity_preferenceController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::readAll
     * @todo   Implement testReadAll().
     */
    public function testReadAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::readAllWithFilter
     * @todo   Implement testReadAllWithFilter().
     */
    public function testReadAllWithFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FSS\Controllers\Shelter_client_identity_preferenceController::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
