<?php
namespace FSS\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 12:58:07.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers FSS\Models\User::validatePassword
     * 
     * @todo Implement testValidatePassword().
     */
    public function testValidatePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\User::verifyPassword
     * 
     * @todo Implement testVerifyPassword().
     */
    public function testVerifyPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\User::authenticate
     * 
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers FSS\Models\User::person
     * 
     * @todo Implement testPerson().
     */
    public function testPerson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
