<?php
namespace FSS\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-20 at 12:58:07.
 */
class UserRoleTest extends \PHPUnit\Framework\TestCase
{

    /**
     *
     * @var User_role
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserRole();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}
}
